# -*- coding: utf-8 -*-
"""workshopDay2P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WngmRSQYd-FrBuNHI-YVRthhpTIbfsG
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("gaming_addiction.csv")
print(df.shape)

if "user_id" in df.columns:
    df = df.drop(columns=["user_id"])

print("\nConverting categorical columns...")

categorical_cols = df.select_dtypes(include=["object"]).columns

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("Dataset Shape After Encoding:", df.shape)

num_cols = df_features.select_dtypes(include=np.number).columns
X = df_features[num_cols].copy()
print("Numeric features used:", X.shape[1])
print(list(X.columns))

print("\nPreparing features...")

X = df.copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\nFinding optimal K...")

wcss = []

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')

# Check if X_scaled actually contains NaN values before imputation
if np.isnan(X_scaled).any():
    print("NaN values found in X_scaled. Imputing with mean...")
    X_scaled = imputer.fit_transform(X_scaled)
    print("NaN values imputed.")

for k in range(1,11):
    model = KMeans(n_clusters=k,
                   random_state=42,
                   n_init=10)

    model.fit(X_scaled)
    wcss.append(model.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,11),wcss,marker="o")
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.grid(True)
plt.show()

print(""" Choose the point where the graph bends. That value is usually the optimal number of clusters. For this example we use K = 3. """)

pca_full = PCA().fit(X_scaled)
cum_var = np.cumsum(pca_full.explained_variance_ratio_)
n_components = np.argmax(cum_var >= 0.90) + 1
print(f"Components needed for 90% variance: {n_components}")
print(f"Variance explained: {cum_var[n_components-1]:.4f}")

pca = PCA(n_components=n_components, random_state=42)
X_pca = pca.fit_transform(X_scaled)

best_k = 3
kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(X_pca)
df_features["cluster"] = cluster_labels
print(pd.Series(cluster_labels).value_counts())

final_sil = silhouette_score(X_pca, cluster_labels)
print("Final silhouette score:", round(final_sil, 4))

pca2 = PCA(n_components=2, random_state=42)
X_2d = pca2.fit_transform(X_scaled)

plt.figure(figsize=(8,6))
colors = ["#4C72B0", "#DD8452", "#55A868"] # Added a third color
for cl in sorted(set(cluster_labels)):
    mask = cluster_labels == cl
    plt.scatter(X_2d[mask,0], X_2d[mask,1], label=f"Cluster {cl}", alpha=0.7, color=colors[cl])
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("KMeans Clusters (k=2) on first 2 principal components")
plt.legend()
plt.grid(alpha=0.3)
plt.show()