# -*- coding: utf-8 -*-
"""workshopDay1-2ndP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lsxUIfKsOddgezxkkTzNoZNUvDfabbN4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.preprocessing import LabelEncoder

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Teen_Mental_Health_Dataset.csv")
print("Dataset Loaded")

df.head()

df.info()

df.columns

print("\n missing values")
print(df.isnull().sum())

print(df.duplicated().sum())

print("\n")
print("="*60)
print("TARGET CLASSES")
print("="*60)

print(df["depression_label"].value_counts())
#check balences

encoder = LabelEncoder() #Creating class "Yes" and "No" to integer value

df["depression_label"] = encoder.fit_transform(df["depression_label"])

print("\nEncoded Classes")

for i, name in enumerate(encoder.classes_):
    print(i, "=", name)

X = df.drop("depression_label", axis=1)

y = df["depression_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))
# X and Y train=80%
# X and Y test=20

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=500) #max value=500
categorical_cols = X_train.select_dtypes(include=['object']).columns
from sklearn.preprocessing import LabelEncoder
for col in categorical_cols:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\n")
print("="*60)
print("MODEL ACCURACY")
print("="*60)

print(f"Accuracy : {accuracy*100:.2f}%")

print("\n")
print("="*60)
print("CLASSIFICATION REPORT")
print("="*60)

print(classification_report(
    y_test,
    y_pred,
    target_names=[str(c) for c in encoder.classes_]
))

cm = confusion_matrix(y_test, y_pred)

print("\n")
print("="*60)
print("CONFUSION MATRIX")
print("="*60)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=encoder.classes_
)

disp.plot(cmap="Blues")

plt.title("Confusion Matrix")

plt.show()

importance = np.mean(np.abs(model.coef_), axis=0)

feature_names = X.columns

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print("\n")
print("="*60)
print("FEATURE IMPORTANCE")
print("="*60)

print(importance_df)

plt.figure(figsize=(10,8))

plt.bar(
    importance_df["Feature"],
    importance_df["Importance"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Importance")

plt.xticks(rotation=20)

plt.show()

