# -*- coding: utf-8 -*-
"""workshopDay2p2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5hjwrvQtEBr83qd5wSHbN-f8pznIwrt
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Wholesale customers data (1).csv")
print(df.shape)

print(df.columns.tolist())

leakage_cols = ["Channel", "Region"]
leakage_df = df[leakage_cols].copy()
df_features = df.drop(columns=leakage_cols)
print("Feature columns:", df_features.columns.tolist())

print(df_features.isnull().sum())

num_cols = df_features.columns.tolist()
X = df_features[num_cols].copy()
print(X.shape)

X_log = np.log1p(X)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_log)
print(X_scaled.shape)

pca_full = PCA().fit(X_scaled)
cum_var = np.cumsum(pca_full.explained_variance_ratio_)
n_components = np.argmax(cum_var >= 0.90) + 1
print(f"Components needed for 90% variance: {n_components}")
print(f"Variance explained: {cum_var[n_components-1]:.4f}")
print("Cumulative variance by component:", np.round(cum_var, 4))

pca = PCA(n_components=n_components, random_state=42)
X_pca = pca.fit_transform(X_scaled)

sil_scores = {}
for k in range(2, 8):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_pca)
    sil_scores[k] = silhouette_score(X_pca, labels)
    print(f"k={k}: silhouette={sil_scores[k]:.4f}")

best_k = max(sil_scores, key=sil_scores.get)
print("\nBest k:", best_k)

kmeans = KMeans(n_clusters=best_k, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(X_pca)
df_features["cluster"] = cluster_labels
print(pd.Series(cluster_labels).value_counts())

final_sil = silhouette_score(X_pca, cluster_labels)
print("Final silhouette score:", round(final_sil, 4))

pca2 = PCA(n_components=2, random_state=42)
X_2d = pca2.fit_transform(X_scaled)

plt.figure(figsize=(8,6))
colors = ["#4C72B0", "#DD8452"]
for cl in sorted(set(cluster_labels)):
    mask = cluster_labels == cl
    plt.scatter(X_2d[mask,0], X_2d[mask,1], label=f"Cluster {cl}", alpha=0.7, color=colors[cl])
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("KMeans Clusters (k=2) on first 2 principal components")
plt.legend()
plt.grid(alpha=0.3)
plt.show()