# -*- coding: utf-8 -*-
"""workshopDay1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8cAVNXNRqHQT8WNuHTeZID-LRR7kxaq
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df.head()

print("Dataset Info")
print("=" * 50)
df.info()
#row column d

df.describe()
#Gives count, mean, min, max,std etc

print(df.isnull().sum())
#Counts empty/missing cells per column.

df.fillna(df.mean(numeric_only=True), inplace=True)
#Any missing numeric value gets replaced with the average of that column

X_train, X_test, y_train, y_test = train_test_split(
      X,
      y,
      test_size=0.2,
      random_state=42
  )

  print("\nTraining Shape:", X_train.shape)
  print("Testing Shape :", X_test.shape)
  #80-20

model = LinearRegression()

model.fit(X_train, y_train)

print("\nModel Training Completed")

y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(comparison.head())
#Runs the trained model actual VS predicted

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("\nEvaluation Metrics")
print("-" * 40)
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R2 Score :", r2)
#explains (1.0=perfect,0=no better than guessing)

coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("\nFeature Importance")
print(coef)
#Shows how much each input pushes the prediction up or down

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Paddy Yield (Kg)")
plt.ylabel("Predicted Paddy Yield (Kg)")
plt.title("Actual vs Predicted")
plt.grid(True)
plt.show()
#The closer the dots hug that line, the better the model.

residuals = y_test - y_pred

plt.figure(figsize=(8,6))
plt.scatter(y_pred, residuals)
plt.axhline(y=0, color='red')
plt.xlabel("Predicted Paddy Yield (Kg)")
plt.ylabel("Residual")
plt.title("Residual Plot")
plt.grid(True)
plt.show()
#actual value - predicted value